spin_manifest_version = 2

[application]
name = "aws-sdk"
version = "0.1.0"
authors = ["Josh Rose <joshrose@hey.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "aws-sdk"

[component.aws-sdk]
source = "main.wasm"
allowed_outbound_hosts = []
[component.aws-sdk.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
